### ISSUE TITLE
[deliverable] Django 1:M Relationships

### ISSUE THREAD

**Issue by romebell** [SEIRFX-822/mysite#6]
## Django 1:M Relationships

Django makes it easy to attach different types of data to your models that define what is saved in your database. It's easy to add integers, floats, dates, datetimes, short text, long text and lots of stuff.

Oh, here's a link to all of the fields Django provides for models, and links to their documentation on [many-to-one relationships](https://docs.djangoproject.com/en/5.0/topics/db/examples/many_to_one/):

Of course, Django also has ways to hook up one-to-many and many-to-many relationships. Django establishes one-to-many relationships using a `model.ForeignKey()` field.

You'll need to add a ForeignKey field to a model to set up the association, then, after that's added, create and run some migrations.

- [x] Create the following models `Artist`, `Album` and `Song` and hook them up to each other:

```python
from django.db import models

class Artist(models.Model):
  name = models.CharField(max_length=100)

  def __str__(self):
    return self.name

class Album(models.Model):
  title = models.CharField(max_length=100)
  artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

  def __str__(self):
    return self.title

class Song(models.Model):
  title = models.CharField(max_length=100)
  album = models.ForeignKey(Album, on_delete=models.CASCADE)
  artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

  def __str__(self):
    return self.title
```

Now that these models are defined, have Python detect the changes and use `manage.py` to create migrations and run them:

```bash
python3 manage.py makemigrations
python3 manage.py migrate
```

Now that relationships have been set up you can create models on the server and save models as fields of other models. Let's practice creating relations by firing up the Django shell. You'll need to import the models from your app to have access to them in the shell.

```bash
python3 manage.py shell
```

```python
# import the application models.
from songs.models import *

# Create an artist, and make sure to save it.
# Other models can't refer to another model until it's saved and has an id.
weezer = Artist(name="Weezer")
weezer.save()

# Create an album with a reference to the artist that's been created.
pinkerton = Album(title="Pinkerton", artist=weezer)
pinkerton.save()

# Save a few songs that were on Pinkerton
song1 = Song(title="El Scorcho", album=pinkerton, artist=weezer)
song1.save()

song2 = Song(title="Getchoo", album=pinkerton, artist=weezer)
song2.save()

song3 = Song(title="No Other One", album=pinkerton, artist=weezer)
song3.save()
```

Run a query to grab all of the song objects and make sure they're saved and retrieved properly. Use a for loop to iterate through each of the songs and print out the songs title, the title of the album, and the name of the artist:

```python
songs = Song.objects.all()
for song in songs:
  print(f'"{song.title}" on {song.album.title} by {song.artist.name}')
```

- [x] Register each model inside of `polls/admin.py`
- [x] Check to see if you are able to see the models inside of the **admin portal**
- [x] Create a new `artist`, `album` and `song` inside of the **admin portal** to make sure it works
- [x] Make a `commit` and `push` to Github

<hr>

## Dango M:M Relationships
- [x] Read up on [Many-to-many relationships](https://docs.djangoproject.com/en/5.0/topics/db/examples/many_to_many/)
- [x] Write in the comments below `3` things you to take away from reading [Many-to-many relationships](https://docs.djangoproject.com/en/5.0/topics/db/examples/many_to_many/)

<hr>

## Dango 1:1 Relationships
- [x] Read up on [one-to-one relationships](https://docs.djangoproject.com/en/5.0/topics/db/examples/one_to_one/)
- [ ] Write in the comments below `3` things you to take away from reading [one-to-one relationships](https://docs.djangoproject.com/en/5.0/topics/db/examples/one_to_one/)

**Comment by soyrvelez** [comment]
**M:M Takeaways**

- You can't associate objects with other models until they have been saved.
- You can associate with one or many objects using `.add` as in `object.modelname.add(obj1, obj2)`
- Using `.add()` more than once won't duplicate the relation
- Objects on each side of the relationship get access to the associated objects of the other model
- You can query using lookups `__` across relationships. This includes the model without the ManyToManyField in its schema

**1:1 Takeaways**

- You can use `hasattr(model, attribute)` to check if an object possesses an attribute.
- You also need to save objects before you can associate them with the other model.
- You can also do queries using lookup fields across relationships

**Comment by dfloresca** [comment]
**M:M Takeaways**
*. can create either object and they can exists independently
*  Need to save both to be able to associate.
*  offers great flexibility when adding and removing. Not able to duplicate relations
**1:1 Takeaways**
* need to save before can associate. 
* Primary attribute in one to one needs to be saved first. 
* hasattr as a way catch exceptions

**Comment by gongt108** [comment]
M:M
- needs to have a value for field "id" before many-to-many relationship can be used
- deleting an instance will remove the association
- reverse m2m queries are supported

1:1
- objects must be saved before it can be assigned to a one-to-one relationship
- can query the objects in either directions
- if on_delete is set to CASCADE, deleting an instance of one model will delete the related instance in the other model

**Comment by mike-gustafson** [comment]
M:M
- Without saving the item first, there's nothing to associate so all entries must be saved before associating
- relations are restricted to singular implementation (no dupes)
- reverse lookups are possible

1:1
- can CASCADE the deletion of objects, but must have the on_delete field set to CASCADE
- Good for putting entries into more defined sub-categories: ie state > city > street > address
- subcategories can always access their parent element.

**Comment by DGWonKanobi** [comment]
1:1 
You can query the models using lookups across relationships.

To define a one-to-one relationship in Django, you use the "OneToOneField" field type in one of the model classes. 

Django provides query capabilities to filter and retrieve objects based on their one-to-one relationships. You can perform queries using methods like get() and filter objects based on attributes of the related model.

M:M
To define a many-to-many relationship, use [ManyToManyField]
 
Django automatically creates an intermediary table to manage the relationship. This table contains foreign keys pointing to both related models.

You can perform complex queries using methods like filter(), exclude(), and annotate()

**Comment by Nimsey** [comment]
m:m
- you need to save before they can be associated
- adding an object of the wrong type will give a TypeError
- relationships can be queried using lookup across relationships

1:1
- you must save an obnject before it can be assigned to a relationship
- to define a 1:1 use ONeToOneField
- cascade will delete both objects
